server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # React Router — toujours servir index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    gzip on;
    gzip_types text/plain application/javascript text/css application/json;
}
